// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Token is the predicate function for token builders.
type Token func(*sql.Selector)
