// Code generated by entc, DO NOT EDIT.

package token

const (
	// Label holds the string label denoting the token type in the database.
	Label = "token"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldURL holds the string denoting the url vertex property in the database.
	FieldURL = "url"
	// FieldURLShortened holds the string denoting the url_shortened vertex property in the database.
	FieldURLShortened = "url_shortened"

	// Table holds the table name of the token in the database.
	Table = "tokens"
)

// Columns holds all SQL columns for token fields.
var Columns = []string{
	FieldID,
	FieldURL,
	FieldURLShortened,
}
